# -*- coding: utf-8 -*-
"""finetune_tinyllama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSP5nAS9ELgar55AmnsvNpXsdu8GOvc6
"""

# ✅ Unsloth clean setup (run this first after restart)
!pip install -q torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 xformers==0.0.32.post2 unsloth

import unsloth   # Must be imported BEFORE transformers or torch-related libs
from unsloth import FastLanguageModel

print("🦥 Unsloth imported successfully — ready to merge!")

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "/content/lora-tinyllama"
save_path = "/content/tinyllama-lora-merged"

model, tokenizer = FastLanguageModel.from_pretrained(
    base_model,
    dtype="float16",
    load_in_4bit=False,
)

from peft import PeftModel

# Load LoRA weights into the model
model = PeftModel.from_pretrained(model, adapter_path)

# Merge LoRA into base model
model = model.merge_and_unload()

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Successfully merged and saved to:", save_path)

# no prompt, just user question

from unsloth import FastLanguageModel
import torch

model_path = "/content/tinyllama-lora-merged"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_path,
    dtype=torch.float16,
    load_in_4bit=False,
)

def chat(prompt, max_new_tokens=200):
    formatted = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(formatted, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print("✅ Model loaded successfully with Unsloth!")

# 🧠 Test it
print(chat("Explain dynamic programming in simple terms."))

# Better Prompt ex. Question + Prompt -> Better Answer 1

def chat(question, max_new_tokens=200):
    # Add a refining instruction to the user’s question
    enhanced_prompt = f"""
You are a helpful assistant that improves the quality of answers by reasoning step-by-step
and giving clear, accurate explanations.

User question: {question}

Please give a complete, well-structured answer.
"""

    formatted = tokenizer.apply_chat_template(
        [{"role": "user", "content": enhanced_prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(formatted, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Example:
print(chat("Explain dynamic programming in simple terms."))

# Better Prompt ex. Question + Prompt -> Better Answer 2


def better_chat(question, max_new_tokens=300):
    system_prompt = """
You are a coding-interview tutor. When the user asks a question:
1) Give a short intuition.
2) Identify the algorithmic pattern (e.g., DP, Greedy, Graph).
3) State State, Base case, Recurrence.
4) Give code outline + complexity.
5) List 2 pitfalls.
Answer concisely and clearly.
"""
    full_prompt = f"{system_prompt}\nUser question: {question}"

    formatted = tokenizer.apply_chat_template(
        [{"role": "user", "content": full_prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(formatted, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Try it
print(better_chat("Explain dynamic programming in simple terms."))

# Better Prompt ex. Question + Prompt -> Better Answer 3

def better_chat(question, max_new_tokens=800):
    enhanced_prompt = f"""
You are a **coding-interview tutor**.
Follow this structure exactly:

1️⃣ Intuition — explain the big idea in 2 sentences.
2️⃣ Pattern — identify if it’s DP, Greedy, Graph, etc.
3️⃣ State, Base case, Recurrence — describe them precisely.
4️⃣ Example — small, concrete example (e.g., climbing stairs).
5️⃣ Code outline — short pseudocode.
6️⃣ Complexity — time and space.
7️⃣ Pitfalls — two common mistakes.
Finally, review your answer and fix any errors.

User question: {question}
"""

    formatted = tokenizer.apply_chat_template(
        [{"role": "user", "content": enhanced_prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(formatted, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Try again:
print(better_chat("Explain dynamic programming in simple terms."))

# Example: clustering questions with K-Means
from sklearn.cluster import KMeans
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt

# 1. Collect questions (you can keep adding your own)
questions = [
    "Explain dynamic programming",
    "What is a greedy algorithm?",
    "How to reverse a linked list?",
    "What is the difference between BFS and DFS?",
    "Explain memoization",
]

# 2. Get embeddings (numerical vectors)
model_emb = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model_emb.encode(questions)

# 3. Apply K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=42)
labels = kmeans.fit_predict(embeddings)

# 4. Visualize or print results
for q, l in zip(questions, labels):
    print(f"Cluster {l}: {q}")

# Optional: visualize clusters
plt.scatter(embeddings[:,0], embeddings[:,1])
plt.title("Question Clusters")
plt.show()

# ==============================================================
#  STEP 0: Environment Setup
# ==============================================================

!pip install -q torch transformers peft accelerate bitsandbytes datasets unsloth

# Optional: check GPU
!nvidia-smi

import unsloth
from unsloth import FastLanguageModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "/content/lora-tinyllama"
save_path = "/content/tinyllama-lora-merged"

model, tokenizer = FastLanguageModel.from_pretrained(
    base_model,
    dtype="float16",
    load_in_4bit=False,
)

model.load_adapter(adapter_path)
model.merge_and_unload()
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Successfully merged and saved to:", save_path)

!pip install -U --force-reinstall --no-cache-dir --no-deps unsloth unsloth_zoo

!ls -lh

!ls -lh /content/lora-tinyllama

!unzip -q /content/lora-tinyllama.zip -d /content/
!ls -lh /content/lora-tinyllama

from unsloth import FastLanguageModel
from peft import PeftModel

# 1️⃣ Load the base model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    dtype="float16",
    load_in_4bit=False,
)

# 2️⃣ Load the LoRA adapter on top of it
lora_model = PeftModel.from_pretrained(model, "/content/lora-tinyllama")

# 3️⃣ Merge LoRA weights into the base model
lora_model = lora_model.merge_and_unload()

# 4️⃣ Save the merged model
save_path = "/content/tinyllama-lora-merged"
lora_model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Successfully merged and saved to:", save_path)

!ls -lh /content/tinyllama-lora-merged

!zip -r tinyllama-lora-merged.zip /content/tinyllama-lora-merged

from unsloth import FastLanguageModel

prompt = tokenizer.apply_chat_template(
    [{"role": "user", "content": "Valid Anagram\nHow do we determine if two strings are anagrams?"}],
    tokenize=False,
    add_generation_prompt=True,
)

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs, max_new_tokens=400)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

!pip uninstall -y unsloth unsloth_zoo
!pip install -q transformers accelerate bitsandbytes torch==2.6.0

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_path = "/content/tinyllama-lora-merged"

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto",
    local_files_only=True
)

def generate(prompt, max_new_tokens=150):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print("✅ TinyLlama chatbot loaded successfully!")

print(generate("Explain dynamic programming in simple terms."))

!ls /content/tinyllama-lora-merged

!ls

# ==============================================================
# STEP 1: Unzip your fine-tuned LoRA adapter
# ==============================================================
!unzip -q /content/lora-tinyllama.zip -d /content/

# Check it extracted correctly
!ls -lh /content/lora-tinyllama

# ==============================================================
# STEP 2: Merge LoRA adapter into base model
# ==============================================================
from unsloth import FastLanguageModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "/content/lora-tinyllama"
save_path = "/content/tinyllama-lora-merged"

model, tokenizer = FastLanguageModel.from_pretrained(base_model, dtype="float16", load_in_4bit=False)
model.load_adapter(adapter_path)
model.merge_and_unload()
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Successfully merged and saved to:", save_path)

!pip install -q --upgrade --force-reinstall --no-cache-dir unsloth unsloth_zoo

from unsloth import FastLanguageModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "/content/lora-tinyllama"
save_path = "/content/tinyllama-lora-merged"

model, tokenizer = FastLanguageModel.from_pretrained(base_model, dtype="float16", load_in_4bit=False)
model.load_adapter(adapter_path)
model.merge_and_unload()
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Successfully merged and saved to:", save_path)

import unsloth
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    dtype="float16",
    load_in_4bit=False,
)
model.load_adapter("/content/lora-tinyllama")
model.merge_and_unload()
model.save_pretrained("/content/tinyllama-lora-merged")
tokenizer.save_pretrained("/content/tinyllama-lora-merged")
print("✅ Successfully merged and saved!")

!pip uninstall -y torchvision

import unsloth
from unsloth import FastLanguageModel

from unsloth import FastLanguageModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "/content/lora-tinyllama"
save_path = "/content/tinyllama-lora-merged"

model, tokenizer = FastLanguageModel.from_pretrained(base_model, dtype="float16", load_in_4bit=False)
model.load_adapter(adapter_path)
model.merge_and_unload()
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Successfully merged and saved to:", save_path)

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

# Load your merged model (adjust path if needed)
model_path = "/content/tinyllama-lora-merged"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto"
)

def refine_prompt(question: str) -> str:
    """Improve a user's question before generating."""
    refinement = (
        "You are a helpful AI assistant that improves technical questions for clarity.\n"
        f"User question: {question}\n"
        "Rewrite the question to make it clear, specific, and detailed about what is being asked.\n"
        "Output only the improved question."
    )
    inputs = tokenizer(refinement, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=120)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def chat_with_model(question: str):
    """Refine → Answer pipeline"""
    refined = refine_prompt(question)
    print(f"\n🪄 Refined Question:\n{refined}\n")
    final_prompt = f"{refined}\nProvide a detailed, structured explanation or solution."
    inputs = tokenizer(final_prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=400)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print("💬 Model Answer:\n", answer)

# Example
chat_with_model("How do I solve two sum problem on Leetcode?")

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_path = "/content/tinyllama-lora-merged"

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto",
    local_files_only=True
)

def refine_prompt(question: str) -> str:
    refinement = (
        "You are a helpful AI assistant that improves technical questions for clarity.\n"
        f"User question: {question}\n"
        "Rewrite the question to make it clear, specific, and detailed about what is being asked.\n"
        "Output only the improved question."
    )
    inputs = tokenizer(refinement, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=120)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def chat_with_model(question: str):
    refined = refine_prompt(question)
    print(f"\n🪄 Refined Question:\n{refined}\n")
    final_prompt = f"{refined}\nProvide a detailed, structured explanation or solution."
    inputs = tokenizer(final_prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=400)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print("💬 Model Answer:\n", answer)

# Example
chat_with_model("How do I solve two sum problem on Leetcode?")

!ls -lh /content/lora-tinyllama

from unsloth import FastLanguageModel

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
adapter_path = "/content/lora-tinyllama"
save_path = "/content/tinyllama-lora-merged"

# 1️⃣ Load base TinyLlama
model, tokenizer = FastLanguageModel.from_pretrained(
    base_model,
    dtype="float16",
    load_in_4bit=False,
)

# 2️⃣ Load and merge your LoRA adapter
model.load_adapter(adapter_path)
model.merge_and_unload()

# 3️⃣ Save the merged model
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Successfully merged and saved to:", save_path)

!pip install -q torchvision

!pip install --force-reinstall torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 xformers==0.0.32.post2 -q